import TanStackQueryProvider from "@/lib/providers/tanstack";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Roboto_Mono as FontMono } from "next/font/google";
import "./globals.css";

const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("h-screen font-mono antialiased", fontMono.variable)}>
        <TanStackQueryProvider>{children}</TanStackQueryProvider>
      </body>
    </html>
  );
}
